window.RADAR_CONFIG = {
  API_ENDPOINT: 'COLE_AQUI_A_URL_/exec_DO_GOOGLE_APPS_SCRIPT',
  WHATSAPP_NUMBER: '5522999680509',
  APP_NAME: 'Radar de Evolução',
  APP_VERSION: '2.4.2',
  REPORT_TITLE: 'Relatório Radar de Evolução',
  CONTEXT_ENDPOINT: '',
  CONTEXT_REFRESH_HOURS: 12
};
